describe('template spec', () => {
  it('Cadastro correto', () => {
    cy.visit('http://localhost:4200')
    cy.get(':nth-child(1) > .mat-mdc-card-content > .mdc-button > .mdc-button__label > span').click()
    cy.get('#mat-input-0').type('Marcio')
    cy.get('#mat-input-1').type('marcio@email.com')
    cy.get('#mat-input-2').type('marcinho66')
    cy.get('#mat-input-3').type('marcinho66')
    cy.get('#mat-input-4').type('31999999999')
    cy.get('#mat-mdc-form-field-label-10 > mat-label').click()
    cy.get('#mat-input-5').type('5/12/2000')
    cy.get('#mat-input-6').type('serrão')
    cy.get('#mat-input-7').type('A')
    cy.get('#mat-input-8').type('Rua dos Sacis')
    cy.get('.ng-tns-c3736059725-9 > .mat-mdc-text-field-wrapper').type('255')
    cy.get('#mat-input-10').type('35774440')
    cy.get('#mat-select-value-1 > .mat-mdc-select-placeholder').click()
    cy.get('#mat-option-0').click()
    cy.get('.ng-tns-c3736059725-13 > .mat-mdc-text-field-wrapper > .mat-mdc-form-field-flex > .mat-mdc-form-field-infix').click()
    cy.get('#mat-option-1').click()
    cy.get('.mdc-button__label').click()
    cy.get('.content > span').contains('Usuário registrado com sucesso!')
    cy.get('body').click()



  })
  it('Cadastro com email ja existente', () => {
    cy.visit('http://localhost:4200')
    cy.get(':nth-child(1) > .mat-mdc-card-content > .mdc-button > .mdc-button__label > span').click()
    cy.get('#mat-input-0').type('Marcio')
    cy.get('#mat-input-1').type('marcio@email.com')
    cy.get('#mat-input-2').type('marcinho66')
    cy.get('#mat-input-3').type('marcinho66')
    cy.get('#mat-input-4').type('31999999999')
    cy.get('#mat-mdc-form-field-label-10 > mat-label').click()
    cy.get('#mat-input-5').type('5/12/2000')
    cy.get('#mat-input-6').type('serrão')
    cy.get('#mat-input-7').type('A')
    cy.get('#mat-input-8').type('Rua dos Sacis')
    cy.get('.ng-tns-c3736059725-9 > .mat-mdc-text-field-wrapper').type('255')
    cy.get('#mat-input-10').type('35774440')
    cy.get('#mat-select-value-1 > .mat-mdc-select-placeholder').click()
    cy.get('#mat-option-0').click()
    cy.get('.ng-tns-c3736059725-13 > .mat-mdc-text-field-wrapper > .mat-mdc-form-field-flex > .mat-mdc-form-field-infix').click()
    cy.get('#mat-option-1').click()
    cy.get('.mdc-button__label').click()
    cy.get('.content > span').contains("E-mail 'marcio@email.com' já está em uso.")
  })
  it('Cadastro com senhas que nãos conferem', () => {
    cy.visit('http://localhost:4200')
    cy.get(':nth-child(1) > .mat-mdc-card-content > .mdc-button > .mdc-button__label > span').click()
    cy.get('#mat-input-0').type('Marcio')
    cy.get('#mat-input-1').type('marcio5@email.com')
    cy.get('#mat-input-2').type('marcinho66')
    cy.get('#mat-input-3').type('marcinho600')
    cy.get('#mat-input-4').type('31999999999')
    cy.get('#mat-mdc-error-3').contains(' As duas senhas devem ser iguais')
    cy.get('#mat-mdc-form-field-label-10 > mat-label').click()
    cy.get('#mat-input-5').type('5/12/2000')
    cy.get('#mat-input-6').type('serrão')
    cy.get('#mat-input-7').type('A')
    cy.get('#mat-input-8').type('Rua dos Sacis')
    cy.get('.ng-tns-c3736059725-9 > .mat-mdc-text-field-wrapper').type('255')
    cy.get('#mat-input-10').type('35774440')
    cy.get('#mat-select-value-1 > .mat-mdc-select-placeholder').click()
    cy.get('#mat-option-0').click()
    cy.get('.ng-tns-c3736059725-13 > .mat-mdc-text-field-wrapper > .mat-mdc-form-field-flex > .mat-mdc-form-field-infix').click()
    cy.get('#mat-option-1').click()
    cy.get('.mdc-button__label').click()
    cy.get('.mat-mdc-dialog-component-host > .content').contains("Preencha todos os campos obrigatórios corretamente")
  })
  it('Login valido (Patient)', () => {
    cy.visit('http://localhost:4200')
    cy.get(':nth-child(2) > .mat-mdc-card-content > .mdc-button > .mdc-button__label > span').click()
    cy.get('#mat-input-0').type('john.patient@email.com')
    cy.get('#mat-input-1').type('12345678')
    cy.get('.login > .mdc-button > .mdc-button__label').click()
  })
  it('Login valido (Physio)', () => {
    cy.visit('http://localhost:4200')
    cy.get(':nth-child(2) > .mat-mdc-card-content > .mdc-button > .mdc-button__label > span').click()
    cy.get('#mat-input-0').type('john.physio@email.com')
    cy.get('#mat-input-1').type('12345678')
    cy.get('.login > .mdc-button > .mdc-button__label').click()
  })
  it('Login invalido', () => {
    cy.visit('http://localhost:4200')
    cy.get(':nth-child(2) > .mat-mdc-card-content > .mdc-button > .mdc-button__label > span').click()
    cy.get('#mat-input-0').type('john.patient@email.com')
    cy.get('#mat-input-1').type('123456789')
    cy.get('.login > .mdc-button > .mdc-button__label').click()
    cy.get('.content > span').contains('Usuário ou senha inválidos.')
  })
  it('Logout', () => {
    cy.visit('http://localhost:4200')
    cy.get(':nth-child(2) > .mat-mdc-card-content > .mdc-button > .mdc-button__label > span').click()
    cy.get('#mat-input-0').type('john.patient@email.com')
    cy.get('#mat-input-1').type('12345678')
    cy.get('.login > .mdc-button > .mdc-button__label').click()
    cy.get('.mat-mdc-menu-trigger > .mat-mdc-button-touch-target').click()
    cy.get('.mat-mdc-menu-item').click()
  })

  it('Agendamento de sessão valida', () => {
    cy.visit('http://localhost:4200')
    cy.get(':nth-child(2) > .mat-mdc-card-content > .mdc-button > .mdc-button__label > span').click()
    cy.get('#mat-input-0').type('john.patient@email.com')
    cy.get('#mat-input-1').type('12345678')
    cy.get('.login > .mdc-button > .mdc-button__label').click()
    cy.get('#mat-input-2').type('10/10/2024')
    cy.get('.mat-mdc-select-placeholder').click()
    cy.get('#mat-option-0').click()
    cy.get('.mat-mdc-select-placeholder').click()
    cy.get('#mat-option-6').click()
    cy.get('.mdc-button__label').click()
    cy.get('.content > span').contains('Sessão marcada com sucesso!')
  })
  it('Agendamento de sessão em finais de semana', () => {
    cy.visit('http://localhost:4200')
    cy.get(':nth-child(2) > .mat-mdc-card-content > .mdc-button > .mdc-button__label > span').click()
    cy.get('#mat-input-0').type('john.patient@email.com')
    cy.get('#mat-input-1').type('12345678')
    cy.get('.login > .mdc-button > .mdc-button__label').click()
    cy.get('#mat-input-2').type('08/10/2024')
    cy.get('.mat-mdc-select-placeholder').click()
    cy.get('#mat-option-0').click()
    cy.get('.mat-mdc-dialog-component-host > .content').type('Não é possível marcar consultas aos fins de semana.')
  })


  it('Agendamento de sessão em datas que ja passaram', () => {
    cy.visit('http://localhost:4200')
    cy.get(':nth-child(2) > .mat-mdc-card-content > .mdc-button > .mdc-button__label > span').click()
    cy.get('#mat-input-0').type('john.patient@email.com')
    cy.get('#mat-input-1').type('12345678')
    cy.get('.login > .mdc-button > .mdc-button__label').click()
    cy.get('#mat-input-2').type('08/10/2020')
    cy.get('.mat-mdc-select-placeholder').click()
    cy.get('#mat-option-0').click()
    cy.get('.content > span').contains('Data da consulta deve ser uma data futura')
  })

})